### ISSUE TITLE
Some question about Discriminative RoI Pooling

### ISSUE THREAD

**Issue by wangjue-wzq** [JialeCao001/D2Det#12]
From your paper, I know that the Discriminative RoI pooling is specifically designed for classification. But after reading your code, I've seen the Discriminative RoI pooling used in SingleRoIExtractor. In other words, it operates on both classification and regression tasks. Am I right in understanding this? In addition, in the ablation experiment, DRP is significantly improved compared to AP of the baseline. Is the increase mainly derived from Defromable ROI pooling or Adaptive pooling? Look forward to your answers.

**Comment by JialeCao001** [comment]
@wangjue-wzq Thanks for interest. Discriminative RoI pooling is specifically designed for classification, where Defromable ROI pooling seems have a good improvement. The regression uses ROI pooling instead of Discriminative RoI pooling. Please refer to the code.  

https://github.com/JialeCao001/D2Det/blob/7bb9e5bc35fc6fad35d51910d012769a13f86de3/configs/D2Det/D2Det_detection_r50_fpn_2x.py#L53

**Comment by wangjue-wzq** [comment]
Thanks！
